version: '3.1'
services:
  web:
    image: odoo:16.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    env_file: 
      - .env

  db:
    image: postgres:15
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    env_file: 
      - .env
    ports:
      - "5432:5432"
      
volumes:
  odoo-web-data:
  odoo-db-data: